Add files via upload
tdb-turma-balaco-baco/bantads pull request #35
Opened 2022-12-07 23:45 UTC by IzaelJ

faltando soma dos saldos negativos e positivos

2022-12-10 00:01 UTC, gjperes requested changes
Principalmente -> rever nomenclatura (RL Clientes ??) 

Fora isso, está tudo ok, eu não sei muito sobre a necessidade do css pra paginação, se possível, esclarecer sobre!

Detalhe que não influencia no review, mas é bacana tomar cuidado: Subir os arquivos já com a formatação do .editorconfig aplicada

2022-12-10 00:01 UTC, gjperes commented on src/app/admin/admin-routing.module.ts
> +  { path: 'admin-rlclientes', redirectTo: 'admin/rlclientes' },
que path é esse cara, eu não abreviaria para RL, sem contexto não dá pra entender o que seria um rl clientes

2022-12-10 00:01 UTC, gjperes commented on src/app/admin/tela-inicio/tela-inicio.component.css
> +.pagination > li > a
Esse CSS é algo já padrão das tabelas bootstrap?

2022-12-10 00:01 UTC, gjperes commented on src/app/admin/tela-inicio/tela-inicio.component.html
> +<div class="row row-cols-1 g-4 p-5">
Usar o comando de formatação, com a extensão do .editorconfig, pra deixar mais padronizado

2022-12-10 00:01 UTC, gjperes commented on src/app/admin/tela-inicio/tela-inicio.component.html
> +              <td> </td>
2 <td> vazios ?

2022-12-10 00:01 UTC, gjperes commented on src/app/admin/tela-inicio/tela-inicio.component.ts
> +    this.gerentes = this.listarTodos(), this.ordemCrescente();
caraca, isso aqui funciona? javascript é bagunça mesmo doideira

2022-12-10 00:01 UTC, gjperes commented on src/app/admin/tela-rlclientes/tela-rlclientes.component.ts
> +export class TelaRlclientesComponent implements OnInit   {
mesmo depois de ler todos os arquivos, sem subir a aplicação com teus commits, ainda não faço a menor ideia do que é um RL Clientes, rever nomenclatura

2022-12-10 00:10 UTC, Mateus-Wosniaki commented on src/app/admin/tela-inicio/tela-inicio.component.html
> +              <td> </td>
Faltou o saldo positivo/negativo

2022-12-10 00:20 UTC, Mateus-Wosniaki commented on src/app/admin/tela-rlclientes/tela-rlclientes.component.ts
> +    return this.clienteService.listarTodos();
Listar todos os clientes não me parece ser uma funcão da cliente service.

Imagino que a cliente service tenha ações/operações que um cliente simples consiga realizar.

Será que um cliente simples poderia ter uma lista de clientes? (Eu colocaria na admin service)

2022-12-10 15:58 UTC, IzaelJ commented on src/app/admin/tela-inicio/tela-inicio.component.css
> +.pagination > li > a
Eu adicionei pra fazer umas mudanças em uma paginação que tinha adicionado e esqueci de remover. Vou remover

2022-12-10 15:58 UTC, IzaelJ commented on src/app/admin/tela-inicio/tela-inicio.component.html
> +<div class="row row-cols-1 g-4 p-5">
Beleza. Acabei me esquecendo

2022-12-10 15:59 UTC, IzaelJ commented on src/app/admin/tela-inicio/tela-inicio.component.html
> +              <td> </td>
Sim, vou adicionar já com o JSON

2022-12-10 15:59 UTC, IzaelJ commented on src/app/admin/tela-inicio/tela-inicio.component.ts
> +    this.gerentes = this.listarTodos(), this.ordemCrescente();
KKKKKKKKKKKKKKKKKKK pensei a mesma coisa

2022-12-10 15:59 UTC, IzaelJ commented on src/app/admin/tela-rlclientes/tela-rlclientes.component.ts
> +export class TelaRlclientesComponent implements OnInit   {
RL Clientes = Relatório Clientes. Vou mudar pra relClientes. o que vocês acham?

2022-12-10 16:00 UTC, IzaelJ commented on src/app/admin/tela-rlclientes/tela-rlclientes.component.ts
> +    return this.clienteService.listarTodos();
Entendi. Vou efetuar a mudança :+1:

2022-12-11 14:53 UTC, gjperes commented on src/app/admin/tela-rlclientes/tela-rlclientes.component.ts
> +export class TelaRlclientesComponent implements OnInit   {
Acho que vale colocar relatorio-clientes , completo mesmo, podendo remover o nome "tela"

2022-12-17 01:16 UTC, gjperes approved these changes

2022-12-17 01:17 UTC, merged